version: "3.3"

services:
  backend:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT:8000
    volumes:
      - .:/api
      - api_node_modules:/api/node_modules
    # networks:
    #   - backend

  frontend:
    env_file: "./cra/.env"
    build:
      context: ./
      dockerfile: ./cra/Dockerfile
    ports:
      - "3000:3000"

volumes:
  api_node_modules: